 import 'package:flutter/material.dart';

Map myData = {
    "Id": 72,
    "parentId": null,
    "Name": "Demo",
    "Username": "Demo_",
    "MobileNo": "7744112233",
    "EmailAddress": "demo_@sonuojha.in",
    "Status": 1,
    "UserType": "User",
    "Category": "Silver",
    "KYCStatus": 3,
    "TotalAchievedIncome": 8023.800272,
    "TotalExpectedIncome": 15000,
    "PackageName": "Package 5000",
    "PackageAmount": 5000,
    "CreatedOn": "0001-01-01T00:00:00",
    "Children": [
      {
        "Id": 7190,
        "parentId": 72,
        "Name": "Demo 1",
        "Username": "Demo_1",
        "MobileNo": "7744112233",
        "EmailAddress": "demo_1@gmail.com",
        "Status": 1,
        "UserType": "User",
        "Category": "Member",
        "KYCStatus": 3,
        "TotalAchievedIncome": 180,
        "TotalExpectedIncome": 3000,
        "PackageName": "Package 1000",
        "PackageAmount": 1000,
        "CreatedOn": "0001-01-01T00:00:00",
        "Children": [],
        "j": null,
        "i": null
      },
      {
        "Id": 7210,
        "parentId": 72,
        "Name": "Demo 2",
        "Username": "Demo_2",
        "MobileNo": "7744112233",
        "EmailAddress": "demo_2@gmail.com",
        "Status": 1,
        "UserType": "User",
        "Category": "Member",
        "KYCStatus": 3,
        "TotalAchievedIncome": 90,
        "TotalExpectedIncome": 1500,
        "PackageName": "Package 500",
        "PackageAmount": 500,
        "CreatedOn": "0001-01-01T00:00:00",
        "Children": [
          {
            "Id": 8339,
            "parentId": 7210,
            "Name": "Demo 3",
            "Username": "Demo_3",
            "MobileNo": "7744112233",
            "EmailAddress": "demo_3@gmail.com",
            "Status": 1,
            "UserType": "User",
            "Category": "Member",
            "KYCStatus": 3,
            "TotalAchievedIncome": 0,
            "TotalExpectedIncome": 0,
            "PackageName": null,
            "PackageAmount": null,
            "CreatedOn": "0001-01-01T00:00:00",
            "Children": [],
            "j": null,
            "i": null
          },
          {
            "Id": 130,
            "parentId": 125,
            "Name": "Demo4",
            "Username": "Demo_4",
            "MobileNo": "7744112233",
            "EmailAddress": "demo_4@gmail.com",
            "Status": 1,
            "UserType": "User",
            "Category": "Member",
            "KYCStatus": 3,
            "TotalAchievedIncome": 150.35,
            "TotalExpectedIncome": 150,
            "PackageName": "Package 50",
            "PackageAmount": 50,
            "CreatedOn": "0001-01-01T00:00:00",
            "Children": [
              {
                "Id": 8339,
                "parentId": 7210,
                "Name": "Demo 5",
                "Username": "Demo_5",
                "MobileNo": "7744112233",
                "EmailAddress": "demo_5@gmail.com",
                "Status": 1,
                "UserType": "User",
                "Category": "Member",
                "KYCStatus": 3,
                "TotalAchievedIncome": 0,
                "TotalExpectedIncome": 0,
                "PackageName": null,
                "PackageAmount": null,
                "CreatedOn": "0001-01-01T00:00:00",
                "Children": [],
                "j": null,
                "i": null
              },
              {
                "Id": 130,
                "parentId": 125,
                "Name": "Demo 6",
                "Username": "Demo_6",
                "MobileNo": "7744112233",
                "EmailAddress": "demo_6@gmail.com",
                "Status": 1,
                "UserType": "User",
                "Category": "Member",
                "KYCStatus": 3,
                "TotalAchievedIncome": 150.35,
                "TotalExpectedIncome": 150,
                "PackageName": "Package 50",
                "PackageAmount": 50,
                "CreatedOn": "0001-01-01T00:00:00",
                "Children": [
                  {
                    "Id": 8339,
                    "parentId": 7210,
                    "Name": "Demo 7",
                    "Username": "Demo_7",
                    "MobileNo": "7744112233",
                    "EmailAddress": "demo_7@gmail.com",
                    "Status": 1,
                    "UserType": "User",
                    "Category": "Member",
                    "KYCStatus": 3,
                    "TotalAchievedIncome": 0,
                    "TotalExpectedIncome": 0,
                    "PackageName": null,
                    "PackageAmount": null,
                    "CreatedOn": "0001-01-01T00:00:00",
                    "Children": [],
                    "j": null,
                    "i": null
                  },
                  {
                    "Id": 130,
                    "parentId": 125,
                    "Name": "Demo 8",
                    "Username": "Demo_8",
                    "MobileNo": "7744112233",
                    "EmailAddress": "demo_8@gmail.com",
                    "Status": 1,
                    "UserType": "User",
                    "Category": "Member",
                    "KYCStatus": 3,
                    "TotalAchievedIncome": 150.35,
                    "TotalExpectedIncome": 150,
                    "PackageName": "Package 50",
                    "PackageAmount": 50,
                    "CreatedOn": "0001-01-01T00:00:00",
                    "Children": [],
                    "j": null,
                    "i": null
                  }
                ],
                "j": null,
                "i": null
              }
            ],
            "j": null,
            "i": null
          }
        ],
        "j": 1475,
        "i": null
      },
      {
        "Id": 7212,
        "parentId": 72,
        "Name": "Demo 9",
        "Username": "Demo_9",
        "MobileNo": "7744112233",
        "EmailAddress": "demo_9@gmail.com",
        "Status": 1,
        "UserType": "User",
        "Category": "Member",
        "KYCStatus": 3,
        "TotalAchievedIncome": 18,
        "TotalExpectedIncome": 300,
        "PackageName": "Package 100",
        "PackageAmount": 100,
        "CreatedOn": "0001-01-01T00:00:00",
        "Children": [],
        "j": null,
        "i": null
      },
      {
        "Id": 7215,
        "parentId": 72,
        "Name": "Demo 10",
        "Username": "Demo_10",
        "MobileNo": "7744112233",
        "EmailAddress": "demo_10@gmail.com",
        "Status": 1,
        "UserType": "User",
        "Category": "Member",
        "KYCStatus": 3,
        "TotalAchievedIncome": 18,
        "TotalExpectedIncome": 300,
        "PackageName": "Package 100",
        "PackageAmount": 100,
        "CreatedOn": "0001-01-01T00:00:00",
        "Children": [],
        "j": null,
        "i": null
      },
      {
        "Id": 7216,
        "parentId": 72,
        "Name": "Demo 11",
        "Username": "Demo_11",
        "MobileNo": "7744112233",
        "EmailAddress": "demo_11@gmail.com",
        "Status": 1,
        "UserType": "User",
        "Category": "Member",
        "KYCStatus": 3,
        "TotalAchievedIncome": 90,
        "TotalExpectedIncome": 1500,
        "PackageName": "Package 500",
        "PackageAmount": 500,
        "CreatedOn": "0001-01-01T00:00:00",
        "Children": [],
        "j": null,
        "i": null
      },
      {
        "Id": 7221,
        "parentId": 72,
        "Name": "Demo 12",
        "Username": "Demo_12",
        "MobileNo": "7744112233",
        "EmailAddress": "demo_12@gmail.com",
        "Status": 1,
        "UserType": "User",
        "Category": "Member",
        "KYCStatus": 3,
        "TotalAchievedIncome": 18,
        "TotalExpectedIncome": 1500,
        "PackageName": "Package 100",
        "PackageAmount": 100,
        "CreatedOn": "0001-01-01T00:00:00",
        "Children": [],
        "j": null,
        "i": null
      }
    ],
    "j": null,
    "i": null
  };
getColor( num packageAmount, num totalAchievedIncome, num totalExpectedIncome) {
    if ( packageAmount > 0 && totalAchievedIncome < totalExpectedIncome) {
      return Colors.green;
    } else if (packageAmount == 0) {
      return Color.fromARGB(255, 220, 21, 6);
    } else if (packageAmount > 0 && totalAchievedIncome >= totalExpectedIncome) {
      return Color.fromARGB(255, 244, 100, 148);
    } else {
      return Colors.green;
    }
  }